require 'rancher/api/models/environment'
require 'rancher/api/models/host'
require 'rancher/api/models/instance'
require 'rancher/api/models/machine'
require 'rancher/api/models/project'
require 'rancher/api/models/service'
